name: storagepilot

services:
  storagepilot:
    image: ${STORAGEPILOT_IMAGE:-rinorbardiqi/storagepilot:full}
    pull_policy: never
    build:
      context: ./app
      target: full
    ports:
      - "${PORT:-3000}:80"
      - "9000:9000"
    volumes:
      - ./data:/data
    environment:
      ENABLED_PROVIDERS: ${ENABLED_PROVIDERS:-gcs,s3,azure}
      MINIO_ROOT_USER: ${MINIO_USER:-storagepilot}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-storagepilot}
    restart: unless-stopped
